CREATE DATABASE IF NOT EXISTS db_bidaia_Gestorea
CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

use db_bidaia_Gestorea;

#IATA taula

INSERT INTO IATA VALUES ('ACA', 'MÉXICO (ACAPULCO)');
INSERT INTO IATA VALUES ('ACE', 'Lanzarote ');
INSERT INTO IATA VALUES ('AGP', 'MALAGA');
INSERT INTO IATA VALUES ('ALC', 'Alicante ');
INSERT INTO IATA VALUES ('AMM', 'JO (Ammán ) AMM');
INSERT INTO IATA VALUES ('AMS', 'HOLANDA Amsterdam ');
INSERT INTO IATA VALUES ('ATH', 'GRECIA ( Atenas)');
INSERT INTO IATA VALUES ('BCN', 'barcelona');
INSERT INTO IATA VALUES ('BER', 'ALEMANIA (Berlín )');
INSERT INTO IATA VALUES ('BIO', 'Bilbao');
INSERT INTO IATA VALUES ('BJZ', 'Badajoz ');
INSERT INTO IATA VALUES ('BKK', 'TAILANDIA Bagkok ');
INSERT INTO IATA VALUES ('BOG', 'COLOMBIA Bogotá ');
INSERT INTO IATA VALUES ('BOS', 'Boston ');
INSERT INTO IATA VALUES ('BRU', 'BELGICA (Bruselas )');
INSERT INTO IATA VALUES ('BSB', 'BRASIL (brasilia)');
INSERT INTO IATA VALUES ('BUE', 'Buenos Aires ');
INSERT INTO IATA VALUES ('CAI', ' EG El Cairo ');
INSERT INTO IATA VALUES ('CAS', ' MARRUECOS (Casablanca) ');
INSERT INTO IATA VALUES ('CCS', 'VENEZUELA ( CARACAS)');
INSERT INTO IATA VALUES ('CDG', 'FRANCIA,París (aeropuerto Charles de Gaulle)');
INSERT INTO IATA VALUES ('CPH', 'DINAMARCA ');
INSERT INTO IATA VALUES ('DTT', 'DETROIT');
INSERT INTO IATA VALUES ('DUB', 'IRLANDA (DUBLIN)');
INSERT INTO IATA VALUES ('DUS', 'ALEMANIA (Dusseldorf )');
INSERT INTO IATA VALUES ('EAS', 'SAN SEBASTIAN');
INSERT INTO IATA VALUES ('FRA', 'ALEMANIA (Frankfurt )');
INSERT INTO IATA VALUES ('FUE', 'FUERTEVENTURA');
INSERT INTO IATA VALUES ('GMZ', 'LA GOMERA');
INSERT INTO IATA VALUES ('GRO', 'Gerona ');
INSERT INTO IATA VALUES ('GRX', 'Granada ');
INSERT INTO IATA VALUES ('GVA', 'SUIZA (Ginebra )');
INSERT INTO IATA VALUES ('HAM', 'ALEMANIA (hamburgo)');
INSERT INTO IATA VALUES ('HEL', 'FINLANDIA (Helsinki )');
INSERT INTO IATA VALUES ('HOU', 'Houston ');
INSERT INTO IATA VALUES ('IBZ', 'Ibiza ');
INSERT INTO IATA VALUES ('IST', 'TR (ESTAMBUL)');
INSERT INTO IATA VALUES ('JFK', 'Nueva York ');
INSERT INTO IATA VALUES ('KIN', 'JAMAICA (kingston)');
INSERT INTO IATA VALUES ('LAX', 'LOS ANGELES');
INSERT INTO IATA VALUES ('LBG', 'FRANCIA ,Le Bourget,');
INSERT INTO IATA VALUES ('LCG', 'La Coruña LCG');
INSERT INTO IATA VALUES ('LGH', 'LONDRES (GATWICK)');
INSERT INTO IATA VALUES ('LHR', 'LONDRES Heathrow');
INSERT INTO IATA VALUES ('LIM', 'PERU ( Lima)');
INSERT INTO IATA VALUES ('LIS', 'PT (lisboa)');
INSERT INTO IATA VALUES ('LPA', 'GRAN CANARIA ');
INSERT INTO IATA VALUES ('LYS', 'FRANCIA (lyon)');
INSERT INTO IATA VALUES ('MAD', 'Madrid');
INSERT INTO IATA VALUES ('MAH', 'MAHON');
INSERT INTO IATA VALUES ('MEL', ' AUSTRALIA Melbourne ');
INSERT INTO IATA VALUES ('MEX', ' México D.F.');
INSERT INTO IATA VALUES ('MIA', 'Miami');
INSERT INTO IATA VALUES ('MIL', ' ITALIA (Milán )');
INSERT INTO IATA VALUES ('MJV', 'Murcia ');
INSERT INTO IATA VALUES ('MOW', ' RUSIA (Moscú ) MOW ');
INSERT INTO IATA VALUES ('MRS', 'FRANCIA (Marsella)');
INSERT INTO IATA VALUES ('MUC', 'ALEMANIA (Munich )');
INSERT INTO IATA VALUES ('NBO', 'KENIA ( Nairobi)');
INSERT INTO IATA VALUES ('ODB', 'Córdoba ');
INSERT INTO IATA VALUES ('ORY', 'FRANCIA (ORLY)');
INSERT INTO IATA VALUES ('OSL', 'NORUEGA (oslo)');
INSERT INTO IATA VALUES ('OVD', 'Asturias ');
INSERT INTO IATA VALUES ('PHL', 'Philadelphia PHL ');
INSERT INTO IATA VALUES ('PMI', 'PALMA DE MALLORCA');
INSERT INTO IATA VALUES ('PNA', 'Pamplona ');
INSERT INTO IATA VALUES ('PRG', 'REPUBLICA CHECA (Praga )');
INSERT INTO IATA VALUES ('RAK', 'MARRUECOS (Marrakech)');
INSERT INTO IATA VALUES ('REU', 'REUS');
INSERT INTO IATA VALUES ('RIO', 'BRASIL (Rio de Janeiro )');
INSERT INTO IATA VALUES ('SAO', ' BRASIL (Sao Paulo )');
INSERT INTO IATA VALUES ('SCQ', 'Santiago de Compostela ');
INSERT INTO IATA VALUES ('SDQ', ' REPUBLICA DOMINICANA (Santo Domingo) ');
INSERT INTO IATA VALUES ('SDR', 'SANTANDER');
INSERT INTO IATA VALUES ('SEA', 'Seattle ');
INSERT INTO IATA VALUES ('SFO', 'SAN FRANCISCO');
INSERT INTO IATA VALUES ('SLM', 'Salamanca ');
INSERT INTO IATA VALUES ('SPC', 'Santa Cruz de la Palma ');
INSERT INTO IATA VALUES ('STN', 'LONDRES ( Stanted)');
INSERT INTO IATA VALUES ('STO', 'SUECIA (Estocolmo)');
INSERT INTO IATA VALUES ('STR', 'ALEMANIA (Stuttgart) ');
INSERT INTO IATA VALUES ('SYD', 'AUSTRALIA (SIYNEY)');
INSERT INTO IATA VALUES ('TFN', 'Tenerife Norte ');
INSERT INTO IATA VALUES ('TFS', 'Tenerife Sur ');
INSERT INTO IATA VALUES ('TUN', 'Túnez ');
INSERT INTO IATA VALUES ('VDE', 'HIERRO ');
INSERT INTO IATA VALUES ('VGO', 'Vigo ');
INSERT INTO IATA VALUES ('VIE', 'AUSTRIA (Viena )');
INSERT INTO IATA VALUES ('VIT', 'VITORIA');
INSERT INTO IATA VALUES ('VLC', 'Valencia ');
INSERT INTO IATA VALUES ('WAS', 'WASHINGTON');
INSERT INTO IATA VALUES ('WAW', 'POLONIA (Varsovia ) WAW ');
INSERT INTO IATA VALUES ('XRY', 'JEREZ DE LA FRONTERA');
INSERT INTO IATA VALUES ('YMQ', 'Montreal, Québec ');
INSERT INTO IATA VALUES ('YOW', ' CA Ottawa, Ontario YOW');
INSERT INTO IATA VALUES ('YTO', 'CA Toronto, Ontario YTO');
INSERT INTO IATA VALUES ('YVR', 'CA VANCOUVER  ');
INSERT INTO IATA VALUES ('ZAZ', 'Zaragoza');
INSERT INTO IATA VALUES ('ZRH', 'SUIZA (Zurich)');

#Herrialdeak Taula

INSERT INTO HERRIALDEAK VALUES ('AR ', 'ARGENTINA');
INSERT INTO HERRIALDEAK VALUES ('AT ', 'AUSTRIA');
INSERT INTO HERRIALDEAK VALUES ('BE', ' BÉLGICA');
INSERT INTO HERRIALDEAK VALUES ('BR ', 'BRASIL');
INSERT INTO HERRIALDEAK VALUES ('CA ', 'CANADA');
INSERT INTO HERRIALDEAK VALUES ('CH ', 'SUIZA');
INSERT INTO HERRIALDEAK VALUES ('CN ', 'CHINA');
INSERT INTO HERRIALDEAK VALUES ('CU', 'CUBA');
INSERT INTO HERRIALDEAK VALUES ('CY ', 'CHIPRE');
INSERT INTO HERRIALDEAK VALUES ('CZ ', 'REPUBLICA CHECA');
INSERT INTO HERRIALDEAK VALUES ('DE ', 'ALEMANIA');
INSERT INTO HERRIALDEAK VALUES ('DK ', 'DINAMARCA');
INSERT INTO HERRIALDEAK VALUES ('EE ', 'ESTONIA');
INSERT INTO HERRIALDEAK VALUES ('EG ', 'EGIPTO');
INSERT INTO HERRIALDEAK VALUES ('ES ', 'ESPAÑA');
INSERT INTO HERRIALDEAK VALUES ('FI ', 'FINLANDIA');
INSERT INTO HERRIALDEAK VALUES ('FR ', 'FRANCIA');
INSERT INTO HERRIALDEAK VALUES ('GB ', 'REINO UNIDO');
INSERT INTO HERRIALDEAK VALUES ('GR ', 'GRECIA');
INSERT INTO HERRIALDEAK VALUES ('GT ', 'GUATEMALA');
INSERT INTO HERRIALDEAK VALUES ('HK ', 'HONG-KONG');
INSERT INTO HERRIALDEAK VALUES ('HR ', 'CROACIA');
INSERT INTO HERRIALDEAK VALUES ('HU ', 'HUNGRIA');
INSERT INTO HERRIALDEAK VALUES ('ID ', 'INDONESIA');
INSERT INTO HERRIALDEAK VALUES ('IE ', 'IRLANDA');
INSERT INTO HERRIALDEAK VALUES ('IL ', 'ISRAEL');
INSERT INTO HERRIALDEAK VALUES ('IN ', 'INDIA');
INSERT INTO HERRIALDEAK VALUES ('IS ', 'ISLANDIA');
INSERT INTO HERRIALDEAK VALUES ('IT ', 'ITALIA');
INSERT INTO HERRIALDEAK VALUES ('JM ', 'JAMAICA');
INSERT INTO HERRIALDEAK VALUES ('JP ', 'JAPÓN');
INSERT INTO HERRIALDEAK VALUES ('KE ', 'KENIA');
INSERT INTO HERRIALDEAK VALUES ('LU ', 'LUXEMBURGO');
INSERT INTO HERRIALDEAK VALUES ('MA', 'MARRUECOS');
INSERT INTO HERRIALDEAK VALUES ('MC ', 'MÓNACO');
INSERT INTO HERRIALDEAK VALUES ('MT', 'MALTA');
INSERT INTO HERRIALDEAK VALUES ('MV ', 'MALDIVAS');
INSERT INTO HERRIALDEAK VALUES ('MX', 'MEXICO');
INSERT INTO HERRIALDEAK VALUES ('NL ', 'PAISES BAJOS');
INSERT INTO HERRIALDEAK VALUES ('NO ', 'NORUEGA');
INSERT INTO HERRIALDEAK VALUES ('PA ', 'PANAMÁ');
INSERT INTO HERRIALDEAK VALUES ('PE ', 'PERÚ');
INSERT INTO HERRIALDEAK VALUES ('PL ', 'POLONIA');
INSERT INTO HERRIALDEAK VALUES ('PR ', 'PUERTO RICO');
INSERT INTO HERRIALDEAK VALUES ('PT ', 'PORTUGAL');
INSERT INTO HERRIALDEAK VALUES ('QA ', 'QATAR');
INSERT INTO HERRIALDEAK VALUES ('RO ', 'RUMANIA');
INSERT INTO HERRIALDEAK VALUES ('RU ', 'RUSIA');
INSERT INTO HERRIALDEAK VALUES ('SC ', ' SEYCHELLES');
INSERT INTO HERRIALDEAK VALUES ('SE ', 'SUECIA');
INSERT INTO HERRIALDEAK VALUES ('SG ', 'SINGAPUR');
INSERT INTO HERRIALDEAK VALUES ('TH ', 'TAILANDIA');
INSERT INTO HERRIALDEAK VALUES ('TN ', 'TÚNEZ');
INSERT INTO HERRIALDEAK VALUES ('TR ', 'TURQUIA');
INSERT INTO HERRIALDEAK VALUES ('TZ ', 'TANZANIA (INCLUYE ZANZIBAR)');
INSERT INTO HERRIALDEAK VALUES ('US ', 'ESTADOS UNIDOS');
INSERT INTO HERRIALDEAK VALUES ('VE ', 'VENEZUELA');
INSERT INTO HERRIALDEAK VALUES ('VN ', 'VIETNAM');
INSERT INTO HERRIALDEAK VALUES ('ZA ', 'SUDÁFRICA');

#Lang_kopurua taula

INSERT INTO LANG_KOPURUA VALUES ('L1', '5 gehienez ( 1 - 5 bitartean)' );
INSERT INTO LANG_KOPURUA VALUES ('L2', '10 gehienez (1 - 10 bitartean)');
INSERT INTO LANG_KOPURUA VALUES ('L3', '20 gehienez (1 - 20 bitartean)');

#Bidaia_motak taula

INSERT INTO BIDAIA_MOTAK VALUES ('B1', 'Ezkongaiak');
INSERT INTO BIDAIA_MOTAK VALUES ('B2', 'Senior');
INSERT INTO BIDAIA_MOTAK VALUES ('B3', 'Taldeak');
INSERT INTO BIDAIA_MOTAK VALUES ('B4', 'Bidaia handiak (helmuga exotikoak + hegaldia + ostatua)');
INSERT INTO BIDAIA_MOTAK VALUES ('B5', 'Eskapada');
INSERT INTO BIDAIA_MOTAK VALUES ('B6', 'Familiak (haur txikiekin)');

#Airelineak taula

INSERT INTO AIRELINEAK VALUES ('2K', 'AVIANCA-Ecuador dba AVIANCA', 'EC');
INSERT INTO AIRELINEAK VALUES ('3P', 'World 2 Fly PT, S.A.', 'PT');
INSERT INTO AIRELINEAK VALUES ('6B*', 'TUIfly Nordic AB', 'CN');
INSERT INTO AIRELINEAK VALUES ('A.C.', 'Air France ', 'FR');
INSERT INTO AIRELINEAK VALUES ('A0', 'BA Euroflyer Limited dba British Airways', 'GB');
INSERT INTO AIRELINEAK VALUES ('AA', 'American Airlines', 'USA');
INSERT INTO AIRELINEAK VALUES ('AM', 'Aerovias de Mexico SA de CV dba AeroMexico', 'MX');
INSERT INTO AIRELINEAK VALUES ('AR', 'Aerolineas Argentinas S.A.', 'AR');
INSERT INTO AIRELINEAK VALUES ('AV', 'Aerovias del Continente Americano S.A. AVIANCA', 'CO');
INSERT INTO AIRELINEAK VALUES ('AY', 'Finnair ', 'FI');
INSERT INTO AIRELINEAK VALUES ('AZ', 'Alitalia', 'IT');
INSERT INTO AIRELINEAK VALUES ('BA', 'British Airways PLC', 'GB');
INSERT INTO AIRELINEAK VALUES ('CL', 'Lufthansa CityLine GmbH', 'DE');
INSERT INTO AIRELINEAK VALUES ('DE', 'Condor Flugdienst GmbH', 'DE');
INSERT INTO AIRELINEAK VALUES ('DL', 'Delta Air Lines Inc', 'USA');
INSERT INTO AIRELINEAK VALUES ('DS', 'Easyjet CH S.A', 'CH');
INSERT INTO AIRELINEAK VALUES ('GL', 'Air GRL', 'GRL');
INSERT INTO AIRELINEAK VALUES ('JJ', 'Tam Linhas Aereas SA dba Latam Airlines Brasil', 'BR');
INSERT INTO AIRELINEAK VALUES ('KL', 'KLM', 'NL');
INSERT INTO AIRELINEAK VALUES ('KN', 'CN United Airlines', 'CN');
INSERT INTO AIRELINEAK VALUES ('LH', 'Lufthansa', 'DE');
INSERT INTO AIRELINEAK VALUES ('LX', 'SWISS Internation Air Lines Ltd', 'CH');
INSERT INTO AIRELINEAK VALUES ('M3', 'BSA - Aerolinhas Brasileiras S.A dba LATAM Cargo Br', 'BR');
INSERT INTO AIRELINEAK VALUES ('MS', 'Egyptair', 'EG');
INSERT INTO AIRELINEAK VALUES ('MT', 'MT Air Travel Ltd dba MT MedAir', 'MT');
INSERT INTO AIRELINEAK VALUES ('N0', 'Norse Atlantic Airways AS', 'NO');
INSERT INTO AIRELINEAK VALUES ('OU', 'HR Airlines d.d.', 'HR');
INSERT INTO AIRELINEAK VALUES ('PC', 'Pegasus Airlines', 'TR');
INSERT INTO AIRELINEAK VALUES ('QR', 'QA Airways Group Q.C.S.C dba QA Airways', 'QA');
INSERT INTO AIRELINEAK VALUES ('RJ', 'Alia - The Royal JOn Airlines dba Royal JOn', 'JO');
INSERT INTO AIRELINEAK VALUES ('RK', 'RYNAIR', 'GB');
INSERT INTO AIRELINEAK VALUES ('S4', 'SATA Internacional - Azores Airlines, S.A.', 'PT');
INSERT INTO AIRELINEAK VALUES ('SN', 'Brussels Airlines', 'BE');
INSERT INTO AIRELINEAK VALUES ('SP', 'SATA (Air Acores)', 'PT');
INSERT INTO AIRELINEAK VALUES ('TK', 'Turkish Airlines Inc', 'TR');
INSERT INTO AIRELINEAK VALUES ('TP', 'TAP PT', 'PT');
INSERT INTO AIRELINEAK VALUES ('TS', 'Air Transat', 'CA');
INSERT INTO AIRELINEAK VALUES ('U2', 'EASYJET UK LIMITED', 'GB');
INSERT INTO AIRELINEAK VALUES ('UA', 'United Airlines Inc', 'USA');
INSERT INTO AIRELINEAK VALUES ('UX', 'Air Europa Lineas Aereas, S.A.', 'ES');
INSERT INTO AIRELINEAK VALUES ('VOY', 'Aerolínea Vueling SA', 'ES');
INSERT INTO AIRELINEAK VALUES ('VS', 'Virgin Atlantic Airways Ltd', 'GB');
INSERT INTO AIRELINEAK VALUES ('WA', 'KLM Cityhopper', 'NL');
INSERT INTO AIRELINEAK VALUES ('WFL', 'World2Fly', 'ES');
INSERT INTO AIRELINEAK VALUES ('WK', 'Edelweiss Air AG', 'CH');
INSERT INTO AIRELINEAK VALUES ('X3*', 'TUIfly Gmbh', 'DE');
INSERT INTO AIRELINEAK VALUES ('X7', 'Challenge Airlines (BE) S.A.', 'BE');
INSERT INTO AIRELINEAK VALUES ('YW', 'Air Nostrum, Lineas aereas del Mediterra neo SA', 'ES');

#Agentzia_motak taula

INSERT INTO AGENTZIA_MOTAK VALUES ('A1', 'Mayorista');
INSERT INTO AGENTZIA_MOTAK VALUES ('A2', 'Minorista');
INSERT INTO AGENTZIA_MOTAK VALUES ('A3', 'Mayorista-minorista');

#Logela_Motak taula

INSERT INTO LOGELA_MOTAK VALUES ('DB', 'Bikoitza');
INSERT INTO LOGELA_MOTAK VALUES ('DUI', 'Bikoitza, erabilpen indibiduala');
INSERT INTO LOGELA_MOTAK VALUES ('SIN', 'Indibiduala');
INSERT INTO LOGELA_MOTAK VALUES ('TPL', 'Hirukoitza');

